apiVersion: v1
kind: Pod
metadata:
  name: nginx-index
  labels:
    app: nginx
spec:
  containers:
  - image: mohamnag/nginx-file-browser
    name:  nginx-index
    ports:
    - containerPort: 80
      name:  nginx
    volumeMounts:
    - name: logs-storage
      mountPath: /opt/www/files
  volumes:
  - name: logs-storage
    persistentVolumeClaim:
      claimName: pvc-logs
