kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-logs
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/logs"
